
export const COMPUTE_MEAN_ACTION_TYPE = 'COMPUTE_MEAN';
export const COMPUTE_ALL_STATS_ACTION_TYPE = 'COMPUTE_ALL_STATS';

export const ADD_TIME_ACTION_TYPE = 'ADD_TIME';

export const CREATE_NEW_SESSION_ACTION_TYPE = 'CREATE_NEW_SESSION';
export const SET_SESSION_NAME_ACTION_TYPE = 'SET_SESSION_NAME';
export const SET_CURRENT_SESSION_ACTION_TYPE = 'SET_CURRENT_SESSION';

export const RESET_SESSION_DATA_TO_DEFAULT_ACTION_TYPE = 'RESET_SESSION_DATA_TO_DEFAULT';
export const UPDATE_SAVED_SESSION_ACTION_TYPE = 'UPDATE_SAVED_SESSION';